[package]
name = "resnet"
version = "0.1.0"
authors = ["LI Rui <lr_cn@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paddle-sys = "0.1.0"
libc = "0.2.81"
